# Generated by Django 2.0.2 on 2018-06-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180628_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='slug', max_length=100),
        ),
    ]
